// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingBMS.API.Data;

#nullable disable

namespace ParkingBMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingBMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("RefreshTokenRevoked")
                        .HasColumnType("bit");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PlannedCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("SlotId", "PlannedCheckIn", "PlannedCheckOut");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ExceptionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<decimal>("AdditionalFee")
                        .HasColumnType("decimal(10,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ExceptionType")
                        .HasColumnType("tinyint");

                    b.Property<int>("HandledByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("HandledByUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingBuilding", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("BuildingId");

                    b.ToTable("ParkingBuildings");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingFloor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FloorId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FloorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("FloorNumber")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("TotalSlots")
                        .HasColumnType("smallint");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("FloorId");

                    b.HasIndex("BuildingId");

                    b.ToTable("ParkingFloors");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("CheckInByStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckOutByStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(12,0)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("SessionType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("SessionId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CheckInByStaffId");

                    b.HasIndex("CheckInTime");

                    b.HasIndex("CheckOutByStaffId");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.HasIndex("LicensePlate", "Status");

                    b.HasIndex("Status", "SlotId");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("SlotId");

                    b.HasIndex("FloorId", "SlotCode")
                        .IsUnique();

                    b.HasIndex("Status", "VehicleType");

                    b.ToTable("ParkingSlots");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,0)");

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(12,0)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("PenaltyFee")
                        .HasColumnType("decimal(12,0)");

                    b.Property<int>("ReceivedByStaffId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId");

                    b.HasIndex("ReceivedByStaffId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.TariffConfig", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<decimal?>("DailyMaxFee")
                        .HasColumnType("decimal(10,0)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("LostTicketFee")
                        .HasColumnType("decimal(10,0)");

                    b.Property<decimal?>("OvertimeFeeRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<short?>("OvertimeHourThreshold")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan?>("PeakEndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("PeakHourRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<TimeSpan?>("PeakStartTime")
                        .HasColumnType("time");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,0)");

                    b.Property<byte>("VehicleType")
                        .HasColumnType("tinyint");

                    b.HasKey("TariffId");

                    b.ToTable("TariffConfigs");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.AppUser", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.ParkingBuilding", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.Booking", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.ParkingSlot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBMS.API.Models.AppUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ExceptionLog", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.AppUser", "HandledByUser")
                        .WithMany("ExceptionLogsHandled")
                        .HasForeignKey("HandledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBMS.API.Models.ParkingSession", "Session")
                        .WithMany("ExceptionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingFloor", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.ParkingBuilding", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingSession", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.Booking", "Booking")
                        .WithMany("Sessions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ParkingBMS.API.Models.AppUser", "CheckInStaff")
                        .WithMany("CheckedInSessionsByStaff")
                        .HasForeignKey("CheckInByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBMS.API.Models.AppUser", "CheckOutStaff")
                        .WithMany("CheckedOutSessionsByStaff")
                        .HasForeignKey("CheckOutByStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParkingBMS.API.Models.ParkingSlot", "Slot")
                        .WithMany("Sessions")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBMS.API.Models.AppUser", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("CheckInStaff");

                    b.Navigation("CheckOutStaff");

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingSlot", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.ParkingFloor", "Floor")
                        .WithMany("Slots")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.Payment", b =>
                {
                    b.HasOne("ParkingBMS.API.Models.AppUser", "ReceivedByStaff")
                        .WithMany("PaymentsReceived")
                        .HasForeignKey("ReceivedByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParkingBMS.API.Models.ParkingSession", "Session")
                        .WithOne("Payment")
                        .HasForeignKey("ParkingBMS.API.Models.Payment", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReceivedByStaff");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.AppUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CheckedInSessionsByStaff");

                    b.Navigation("CheckedOutSessionsByStaff");

                    b.Navigation("ExceptionLogsHandled");

                    b.Navigation("PaymentsReceived");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.Booking", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingBuilding", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingFloor", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingSession", b =>
                {
                    b.Navigation("ExceptionLogs");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ParkingBMS.API.Models.ParkingSlot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
